from typing import TypedDict, List, Optional, Dict, Literal

class GenerateState(TypedDict):
    '''Defines the state of the graph which generates context for the job description'''
    user_context: str
    job_description: str
    context: str
    model_used: Optional[str]
    prompt_version: Optional[str]


class DraftState(TypedDict):
    '''Defines the state of the graph which drafts specific messages[emails, cover letters, linkedin messages] based on the context generated by the graph above'''
    user_details: str
    context: str
    type: Literal['email', 'cover_letter','linkedin_message']
    email: dict
    linkedin_message: dict
    cover_letter: dict
    feedback: str
    model_used: Optional[str]
    prompt_version: Optional[str]

