from typing import TypedDict, List, Optional, Dict, Literal

class GenerateState(TypedDict):
    '''Defines the state of the graph which generates context for the job description'''
    user_context: str
    job_description: str
    context: str
    # Optional: GitHub profile URL — if provided, README summaries are prepended to user_context
    github_url: Optional[str]
    model_used: Optional[str]
    prompt_version: Optional[str]


class GitHubScrapeState(TypedDict):
    '''State for the standalone GitHub README scrape + summarise graph'''
    github_url: str
    # Resulting enriched context to be saved back to the user profile
    github_context: str


class DraftState(TypedDict):
    '''Defines the state of the graph which drafts specific messages[emails, cover letters, linkedin messages] based on the context generated by the graph above'''
    user_details: str
    context: str
    type: Literal['email', 'cover_letter','linkedin_message']
    email: dict
    linkedin_message: dict
    cover_letter: dict
    feedback: str
    model_used: Optional[str]
    prompt_version: Optional[str]

